title: Xlabz Tech DEX 
author: William Bermudez
email: wbermudez@xlabz.tech
theme: minima
description: > # this means to ignore newlines until "baseurl:"
Using open sourced code found here on github I plan on created a DEX, to add a token I forked from safemoon into a liquidity pool, to allow users easy acces to gain their crypto to spend on my eCommerce stores.

# social links

github_username:  github.com/william7829

show_excerpts: true # set to false to remove excerpts on the homepage
